# Problem Statement:

1.	In File1, you have to derive another variable “Parent ID”.
  	Example - Suppose, you have an initial mapping of “Order ID” and “Extension Of” as:
Order ID	Extension Of
SL384	
SL10046	SL384
SL11995	SL10046
  The new table which has the “Parent ID” column will look like - 
Order ID	Extension Of	Parent ID
SL384		SL384
SL10046	SL384	SL384
SL11995	SL10046	SL384
	
Save the output as “parent_ids.csv”

In [8]:
import pandas as pd
import numpy as np
pd.options.display.max_rows=None

In [9]:
import os
os.chdir('C:\\Users\\Admin\\Desktop\\Data\\GOR- Data Scientist- Assignment\\Scientist - Assignment')
data_extension=pd.read_csv('data_extension.csv')
#data_extension['PartNo']=data_extension['Extension Of'].fillna(data_extension['Order ID'],inplace=True)
data_extension.head(176)

        Order ID Extension Of  Archive  Quantity       City
0          SL158          NaN        0         1  Bangalore
1          SL159          NaN        0         1  Bangalore
2          SL160          NaN        0         1  Bangalore
3          SL162          NaN        0         1  Bangalore
4          SL164          NaN        0         1  Bangalore
5          SL165          NaN        0         1  Bangalore
6          SL168          NaN        0         1  Bangalore
7          SL169          NaN        0         1  Bangalore
8          SL170          NaN        0         1  Bangalore
9          SL171          NaN        0         1  Bangalore
10         SL172          NaN        0         1  Bangalore
11         SL176          NaN        0         1  Bangalore
12         SL177          NaN        0         1  Bangalore
13         SL178          NaN        0         1  Bangalore
14         SL179          NaN        0         1  Bangalore
15         SL180          NaN        0         1  Bangalore
16         SL183          NaN        0         1  Bangalore
17         SL184          NaN        0         1  Bangalore
18         SL189          NaN        0         1  Bangalore
19         SL190          NaN        0         1  Bangalore
20         SL191          NaN        0         1  Bangalore
21         SL192          NaN        0         1  Bangalore
22         SL193          NaN        0         1  Bangalore
23         SL195          NaN        0         1  Bangalore
24         SL196          NaN        0         1  Bangalore
25         SL199          NaN        0         1  Bangalore
26         SL200          NaN        0         1  Bangalore
27         SL201          NaN        0         1  Bangalore
28         SL207          NaN        0         1  Bangalore
29         SL208          NaN        0         1  Bangalore
30         SL209          NaN        0         1  Bangalore
31         SL218          NaN        0         1  Bangalore
32         SL219          NaN        0         1  Bangalore
33         SL223          NaN        0         1  Bangalore
34         SL224          NaN        0         1  Bangalore
35         SL225          NaN        0         1  Bangalore
36         SL226          NaN        0         1  Bangalore
37         SL227          NaN        0         1  Bangalore
38         SL229          NaN        0         1  Bangalore
39         SL232          NaN        0         1  Bangalore
40         SL233          NaN        0         1  Bangalore
41         SL234          NaN        0         1  Bangalore
42         SL235          NaN        0         1  Bangalore
43         SL239          NaN        0         1  Bangalore
44         SL240          NaN        0         1  Bangalore
45         SL241          NaN        0         1  Bangalore
46         SL242          NaN        0         1  Bangalore
47         SL243          NaN        0         1  Bangalore
48         SL251          NaN        0         1  Bangalore
49         SL252          NaN        0         1  Bangalore
50         SL257          NaN        0         1  Bangalore
51         SL258          NaN        0         1  Bangalore
52         SL260          NaN        0         1  Bangalore
53         SL261          NaN        0         1  Bangalore
54         SL262          NaN        0         1  Bangalore
55         SL266          NaN        0         1  Bangalore
56         SL267          NaN        0         1  Bangalore
57         SL268          NaN        0         1  Bangalore
58         SL269          NaN        0         1  Bangalore
59         SL277          NaN        0         1  Bangalore
60         SL278          NaN        0         1  Bangalore
61         SL279          NaN        0         1  Bangalore
62         SL280          NaN        0         1  Bangalore
63         SL281          NaN        0         1  Bangalore
64         SL287          NaN        0         1  Bangalore
65         SL288          NaN        0         1  Bangalore
66         SL289          NaN        0         1  Bangalore
67         SL300          NaN        0         1  Bangalore
68         SL301          NaN        0         1  Bangalore
69         SL302          NaN        0         1  Bangalore
70         SL303          NaN        0         1  Bangalore
71         SL304          NaN        0         1  Bangalore
72         SL305          NaN        0         1  Bangalore
73         SL315          NaN        0         1  Bangalore
74         SL316          NaN        0         1  Bangalore
75         SL322          NaN        0         1  Bangalore
76         SL323          NaN        0         1  Bangalore
77         SL327          NaN        0         1  Bangalore
78         SL328          NaN        0         1  Bangalore
79         SL333          NaN        0         1  Bangalore
80         SL334          NaN        0         1  Bangalore
81         SL335          NaN        0         1  Bangalore
82         SL336          NaN        0         1  Bangalore
83         SL337          NaN        0         1  Bangalore
84         SL340          NaN        0         1  Bangalore
85         SL341          NaN        0         1  Bangalore
86         SL342          NaN        0         1  Bangalore
87         SL343          NaN        0         1  Bangalore
88         SL344          NaN        0         1  Bangalore
89         SL345          NaN        0         1  Bangalore
90         SL350          NaN        0         1  Bangalore
91         SL351          NaN        0         1  Bangalore
92         SL352          NaN        0         1  Bangalore
93         SL353          NaN        0         1  Bangalore
94         SL354          NaN        0         1  Bangalore
95         SL355          NaN        0         1  Bangalore
96         SL363          NaN        0         1  Bangalore
97         SL364          NaN        0         1  Bangalore
98         SL365          NaN        0         1  Bangalore
99         SL366          NaN        0         1  Bangalore
100        SL367          NaN        0         1  Bangalore
101        SL368          NaN        0         1  Bangalore
102        SL369          NaN        0         1  Bangalore
103        SL370          NaN        0         1  Bangalore
104        SL376          NaN        0         1  Bangalore
105        SL377          NaN        0         1  Bangalore
106        SL378          NaN        0         1  Bangalore
107        SL379          NaN        0         1  Bangalore
108        SL380          NaN        0         1  Bangalore
109        SL381          NaN        0         1  Bangalore
110        SL382          NaN        0         1  Bangalore
111        SL383          NaN        0         1  Bangalore
112        SL384          NaN        0         1  Bangalore
113        SL385          NaN        0         1  Bangalore
114       SL1217       SL1134        0         1  Bangalore
115       SL1452       SL1011        0         1  Bangalore
116       SL4316       SL3691        0         1  Bangalore
117       SL4317       SL3718        0         1  Bangalore
118       SL4348       SL3727        0         1  Bangalore
119       SL4381       SL3695        0         1  Bangalore
120       SL4681       SL3720        0         1  Bangalore
121       SL4738       SL3716        0         1  Bangalore
122       SL5319       SL3721        0         1  Bangalore
123       SL5520       SL5242        0         1  Bangalore
124       SL5703       SL5246        0         1  Bangalore
125       SL6132       SL5245        0         1  Bangalore
126       SL6244       SL5254        0         1  Bangalore
127       SL6855       SL5255        0         1  Bangalore
128       SL6997       SL3686        0         1  Bangalore
129   SLB1253161      SL11365        0         1  Bangalore
130   SLB2970530      SL11384        0         1  Bangalore
131  SLB27287329      SL11377        0         1  Bangalore
132  SLB36502009      SL10134        0         1  Bangalore
133  SLB81913180      SL11333        0         1  Bangalore
134  SLB82838226      SL10143        0         1  Bangalore
135  SLB90244936      SL11338        0         1  Bangalore
136  SLB99701642      SL10126        0         1  Bangalore
137      SL11995      SL10046        0         1  Hyderabad
138   SLH5317239      SL10070        0         1  Hyderabad
139  SLH22149557      SL11364        0         1  Hyderabad
140  SLH44727392      SL11335        0         1  Hyderabad
141  SLH45803004      SL10004        0         1  Hyderabad
142  SLH57801072      SL10058        0         1  Hyderabad
143  SLH74470000      SL11366        0         1  Hyderabad
144  SLH79063451      SL10092        0         1  Hyderabad
145       SL1134          NaN        0         1  Bangalore
146       SL1011          NaN        0         1  Bangalore
147       SL3686          NaN        0         1  Bangalore
148       SL3691          NaN        0         1  Bangalore
149       SL3695          NaN        0         1  Bangalore
150       SL3716          NaN        0         1  Bangalore
151       SL3718          NaN        0         1  Bangalore
152       SL3720          NaN        0         1  Bangalore
153       SL3721          NaN        0         1  Bangalore
154       SL3727          NaN        0         1  Bangalore
155       SL5242          NaN        0         1  Bangalore
156       SL5245          NaN        0         1  Bangalore
157       SL5246          NaN        0         1  Bangalore
158       SL5254          NaN        0         1  Bangalore
159       SL5255          NaN        0         1  Bangalore
160      SL10126          NaN        0         1  Bangalore
161      SL10134          NaN        0         1  Bangalore
162      SL10143          NaN        0         1  Bangalore
163      SL11333          NaN        0         1  Bangalore
164      SL11338          NaN        0         1  Bangalore
165      SL11365          NaN        0         1  Bangalore
166      SL11377          NaN        0         1  Bangalore
167      SL11384          NaN        0         1  Bangalore
168      SL10004          NaN        0         1  Hyderabad
169      SL10046        SL384        0         1  Hyderabad
170      SL10058          NaN        0         1  Hyderabad
171      SL10070          NaN        0         1  Hyderabad
172      SL10092        SL171        0         1  Hyderabad
173      SL11335          NaN        0         1  Hyderabad
174      SL11364          NaN        0         1  Hyderabad
175      SL11366          NaN        0         1  Hyderabad

In [10]:
## Create a new column called 'Parent ID' and this column will replace the null values with the Order ID of that particular row
for index,row in data_extension.iterrows():
    if(pd.isnull(row['Extension Of'])):
            #print(data_extension.loc[:index,:])
            data_extension.loc[index:index,'PartNo']=data_extension.loc[index:index,'Order ID']

## List of all the Unique order id's present in the Parent ID 
a=list(set(data_extension.loc[0:176,'PartNo']))

for index,row in data_extension.iterrows():
    if (pd.notnull(row['Extension Of'])):
        if(list(data_extension.loc[index:index,'Extension Of'])[0] in a):
             data_extension.loc[index:index,'PartNo']=row['Extension Of']
        if(list(data_extension.loc[index:index,'Extension Of'])[0] not in a):
            data_extension.loc[index:index,'PartNo']=row['Extension Of']
            term=list(set(data_extension.loc[index:index,'Extension Of']))[0]
            cad=list(data_extension.loc[data_extension['Order ID']==term,'Extension Of'])[0]
            data_extension.loc[index:index,'PartNo']=cad

In [11]:
data_extension.head(176)

        Order ID Extension Of  Archive  Quantity       City   PartNo
0          SL158          NaN        0         1  Bangalore    SL158
1          SL159          NaN        0         1  Bangalore    SL159
2          SL160          NaN        0         1  Bangalore    SL160
3          SL162          NaN        0         1  Bangalore    SL162
4          SL164          NaN        0         1  Bangalore    SL164
5          SL165          NaN        0         1  Bangalore    SL165
6          SL168          NaN        0         1  Bangalore    SL168
7          SL169          NaN        0         1  Bangalore    SL169
8          SL170          NaN        0         1  Bangalore    SL170
9          SL171          NaN        0         1  Bangalore    SL171
10         SL172          NaN        0         1  Bangalore    SL172
11         SL176          NaN        0         1  Bangalore    SL176
12         SL177          NaN        0         1  Bangalore    SL177
13         SL178          NaN        0         1  Bangalore    SL178
14         SL179          NaN        0         1  Bangalore    SL179
15         SL180          NaN        0         1  Bangalore    SL180
16         SL183          NaN        0         1  Bangalore    SL183
17         SL184          NaN        0         1  Bangalore    SL184
18         SL189          NaN        0         1  Bangalore    SL189
19         SL190          NaN        0         1  Bangalore    SL190
20         SL191          NaN        0         1  Bangalore    SL191
21         SL192          NaN        0         1  Bangalore    SL192
22         SL193          NaN        0         1  Bangalore    SL193
23         SL195          NaN        0         1  Bangalore    SL195
24         SL196          NaN        0         1  Bangalore    SL196
25         SL199          NaN        0         1  Bangalore    SL199
26         SL200          NaN        0         1  Bangalore    SL200
27         SL201          NaN        0         1  Bangalore    SL201
28         SL207          NaN        0         1  Bangalore    SL207
29         SL208          NaN        0         1  Bangalore    SL208
30         SL209          NaN        0         1  Bangalore    SL209
31         SL218          NaN        0         1  Bangalore    SL218
32         SL219          NaN        0         1  Bangalore    SL219
33         SL223          NaN        0         1  Bangalore    SL223
34         SL224          NaN        0         1  Bangalore    SL224
35         SL225          NaN        0         1  Bangalore    SL225
36         SL226          NaN        0         1  Bangalore    SL226
37         SL227          NaN        0         1  Bangalore    SL227
38         SL229          NaN        0         1  Bangalore    SL229
39         SL232          NaN        0         1  Bangalore    SL232
40         SL233          NaN        0         1  Bangalore    SL233
41         SL234          NaN        0         1  Bangalore    SL234
42         SL235          NaN        0         1  Bangalore    SL235
43         SL239          NaN        0         1  Bangalore    SL239
44         SL240          NaN        0         1  Bangalore    SL240
45         SL241          NaN        0         1  Bangalore    SL241
46         SL242          NaN        0         1  Bangalore    SL242
47         SL243          NaN        0         1  Bangalore    SL243
48         SL251          NaN        0         1  Bangalore    SL251
49         SL252          NaN        0         1  Bangalore    SL252
50         SL257          NaN        0         1  Bangalore    SL257
51         SL258          NaN        0         1  Bangalore    SL258
52         SL260          NaN        0         1  Bangalore    SL260
53         SL261          NaN        0         1  Bangalore    SL261
54         SL262          NaN        0         1  Bangalore    SL262
55         SL266          NaN        0         1  Bangalore    SL266
56         SL267          NaN        0         1  Bangalore    SL267
57         SL268          NaN        0         1  Bangalore    SL268
58         SL269          NaN        0         1  Bangalore    SL269
59         SL277          NaN        0         1  Bangalore    SL277
60         SL278          NaN        0         1  Bangalore    SL278
61         SL279          NaN        0         1  Bangalore    SL279
62         SL280          NaN        0         1  Bangalore    SL280
63         SL281          NaN        0         1  Bangalore    SL281
64         SL287          NaN        0         1  Bangalore    SL287
65         SL288          NaN        0         1  Bangalore    SL288
66         SL289          NaN        0         1  Bangalore    SL289
67         SL300          NaN        0         1  Bangalore    SL300
68         SL301          NaN        0         1  Bangalore    SL301
69         SL302          NaN        0         1  Bangalore    SL302
70         SL303          NaN        0         1  Bangalore    SL303
71         SL304          NaN        0         1  Bangalore    SL304
72         SL305          NaN        0         1  Bangalore    SL305
73         SL315          NaN        0         1  Bangalore    SL315
74         SL316          NaN        0         1  Bangalore    SL316
75         SL322          NaN        0         1  Bangalore    SL322
76         SL323          NaN        0         1  Bangalore    SL323
77         SL327          NaN        0         1  Bangalore    SL327
78         SL328          NaN        0         1  Bangalore    SL328
79         SL333          NaN        0         1  Bangalore    SL333
80         SL334          NaN        0         1  Bangalore    SL334
81         SL335          NaN        0         1  Bangalore    SL335
82         SL336          NaN        0         1  Bangalore    SL336
83         SL337          NaN        0         1  Bangalore    SL337
84         SL340          NaN        0         1  Bangalore    SL340
85         SL341          NaN        0         1  Bangalore    SL341
86         SL342          NaN        0         1  Bangalore    SL342
87         SL343          NaN        0         1  Bangalore    SL343
88         SL344          NaN        0         1  Bangalore    SL344
89         SL345          NaN        0         1  Bangalore    SL345
90         SL350          NaN        0         1  Bangalore    SL350
91         SL351          NaN        0         1  Bangalore    SL351
92         SL352          NaN        0         1  Bangalore    SL352
93         SL353          NaN        0         1  Bangalore    SL353
94         SL354          NaN        0         1  Bangalore    SL354
95         SL355          NaN        0         1  Bangalore    SL355
96         SL363          NaN        0         1  Bangalore    SL363
97         SL364          NaN        0         1  Bangalore    SL364
98         SL365          NaN        0         1  Bangalore    SL365
99         SL366          NaN        0         1  Bangalore    SL366
100        SL367          NaN        0         1  Bangalore    SL367
101        SL368          NaN        0         1  Bangalore    SL368
102        SL369          NaN        0         1  Bangalore    SL369
103        SL370          NaN        0         1  Bangalore    SL370
104        SL376          NaN        0         1  Bangalore    SL376
105        SL377          NaN        0         1  Bangalore    SL377
106        SL378          NaN        0         1  Bangalore    SL378
107        SL379          NaN        0         1  Bangalore    SL379
108        SL380          NaN        0         1  Bangalore    SL380
109        SL381          NaN        0         1  Bangalore    SL381
110        SL382          NaN        0         1  Bangalore    SL382
111        SL383          NaN        0         1  Bangalore    SL383
112        SL384          NaN        0         1  Bangalore    SL384
113        SL385          NaN        0         1  Bangalore    SL385
114       SL1217       SL1134        0         1  Bangalore   SL1134
115       SL1452       SL1011        0         1  Bangalore   SL1011
116       SL4316       SL3691        0         1  Bangalore   SL3691
117       SL4317       SL3718        0         1  Bangalore   SL3718
118       SL4348       SL3727        0         1  Bangalore   SL3727
119       SL4381       SL3695        0         1  Bangalore   SL3695
120       SL4681       SL3720        0         1  Bangalore   SL3720
121       SL4738       SL3716        0         1  Bangalore   SL3716
122       SL5319       SL3721        0         1  Bangalore   SL3721
123       SL5520       SL5242        0         1  Bangalore   SL5242
124       SL5703       SL5246        0         1  Bangalore   SL5246
125       SL6132       SL5245        0         1  Bangalore   SL5245
126       SL6244       SL5254        0         1  Bangalore   SL5254
127       SL6855       SL5255        0         1  Bangalore   SL5255
128       SL6997       SL3686        0         1  Bangalore   SL3686
129   SLB1253161      SL11365        0         1  Bangalore  SL11365
130   SLB2970530      SL11384        0         1  Bangalore  SL11384
131  SLB27287329      SL11377        0         1  Bangalore  SL11377
132  SLB36502009      SL10134        0         1  Bangalore  SL10134
133  SLB81913180      SL11333        0         1  Bangalore  SL11333
134  SLB82838226      SL10143        0         1  Bangalore  SL10143
135  SLB90244936      SL11338        0         1  Bangalore  SL11338
136  SLB99701642      SL10126        0         1  Bangalore  SL10126
137      SL11995      SL10046        0         1  Hyderabad    SL384
138   SLH5317239      SL10070        0         1  Hyderabad  SL10070
139  SLH22149557      SL11364        0         1  Hyderabad  SL11364
140  SLH44727392      SL11335        0         1  Hyderabad  SL11335
141  SLH45803004      SL10004        0         1  Hyderabad  SL10004
142  SLH57801072      SL10058        0         1  Hyderabad  SL10058
143  SLH74470000      SL11366        0         1  Hyderabad  SL11366
144  SLH79063451      SL10092        0         1  Hyderabad    SL171
145       SL1134          NaN        0         1  Bangalore   SL1134
146       SL1011          NaN        0         1  Bangalore   SL1011
147       SL3686          NaN        0         1  Bangalore   SL3686
148       SL3691          NaN        0         1  Bangalore   SL3691
149       SL3695          NaN        0         1  Bangalore   SL3695
150       SL3716          NaN        0         1  Bangalore   SL3716
151       SL3718          NaN        0         1  Bangalore   SL3718
152       SL3720          NaN        0         1  Bangalore   SL3720
153       SL3721          NaN        0         1  Bangalore   SL3721
154       SL3727          NaN        0         1  Bangalore   SL3727
155       SL5242          NaN        0         1  Bangalore   SL5242
156       SL5245          NaN        0         1  Bangalore   SL5245
157       SL5246          NaN        0         1  Bangalore   SL5246
158       SL5254          NaN        0         1  Bangalore   SL5254
159       SL5255          NaN        0         1  Bangalore   SL5255
160      SL10126          NaN        0         1  Bangalore  SL10126
161      SL10134          NaN        0         1  Bangalore  SL10134
162      SL10143          NaN        0         1  Bangalore  SL10143
163      SL11333          NaN        0         1  Bangalore  SL11333
164      SL11338          NaN        0         1  Bangalore  SL11338
165      SL11365          NaN        0         1  Bangalore  SL11365
166      SL11377          NaN        0         1  Bangalore  SL11377
167      SL11384          NaN        0         1  Bangalore  SL11384
168      SL10004          NaN        0         1  Hyderabad  SL10004
169      SL10046        SL384        0         1  Hyderabad    SL384
170      SL10058          NaN        0         1  Hyderabad  SL10058
171      SL10070          NaN        0         1  Hyderabad  SL10070
172      SL10092        SL171        0         1  Hyderabad    SL171
173      SL11335          NaN        0         1  Hyderabad  SL11335
174      SL11364          NaN        0         1  Hyderabad  SL11364
175      SL11366          NaN        0         1  Hyderabad  SL11366

2.	In File2, you have to split both the start and end dates into intervals of 30 days, and derive two new variables “split start date” and “split end date”.
Example: The below example illustrates how split dates are created when the Start Date is “01/05/2017” and the End Date is “06/07/2017” 
Suppose, an order have start and end dates as below
Order Id	Start Date	End Date
1	01/05/2017	06/07/2017
The new table with ‘split start date’ and ‘split end date’ will look like
Order Id	Start Date	End Date	Split start  Date	Split End Date
1	01/05/2017	06/07/2017	01/05/2017	30/05/2017
1	01/05/2017	06/07/2017	31/05/2017	29/06/2017
1	01/05/2017	06/07/2017	30/06/2017	06/07/2017
             Also, save the output as “split_dates.csv”
Perform the above two tasks in a single script in R/Python and share it as “task.R”/”task.py” . (Please make comments to the code) and share the output in .csv format.

In [12]:
import os
os.chdir('C:\\Users\\Admin\\Desktop\\Data\\GOR- Data Scientist- Assignment\\Scientist - Assignment')
data_date=pd.read_csv('data_date.csv')
#data_extension['PartNo']=data_extension['Extension Of'].fillna(data_extension['Order ID'],inplace=True)
data_date.head()

  Order ID  Archive  Quantity Start Date    End Date       City
0    SL158        0         1   9/8/2015    9/9/2015  Bangalore
1    SL159        0         1   9/8/2015    9/9/2015  Bangalore
2    SL160        0         1   9/8/2015    9/9/2015  Bangalore
3    SL162        0         1  9/10/2015   9/11/2015  Bangalore
4    SL164        0         1  9/11/2015  12/10/2015  Bangalore

In [13]:
## Creating the required columns
## Converting the date fields into datetime datatype
data_date['End Date']=pd.to_datetime(data_date['End Date'])
data_date['Start Date']=pd.to_datetime(data_date['Start Date'])

##Calculating the difference between the End Date and Start Date
data_date['Difference']=data_date['End Date']-data_date['Start Date']

## Converting the difference into the Numeric Format
data_date['Difference'] = data_date['Difference'] / np.timedelta64(1, 'D')

In [14]:
## Creating the new columns to capture the results, default populated with Start Date and End Date values
data_date['Split Start Date']=data_date['Start Date']
data_date['Split End Date']=data_date['End Date']

Empty DataFrame
Columns: [Order ID, Start Date, End Date, Split Start Date, Split End Date, Difference]
Index: []

In [70]:
## Creating the new dataframe to capture the transformed results
df_new=pd.DataFrame(columns=['Order ID','Start Date','End Date','Split Start Date','Split End Date','Difference'])
df_new

from datetime import timedelta 
for index,row in data_date.iterrows():
    ## Identifying the records which has difference greater than 30
    if(list(data_date.loc[index:index,'Difference'])[0]>30):
        days_30=list(data_date.loc[index:index,'Difference'])[0]/30
        days_30_b=days_30
        days_changed=0
        days_decimal=0
        new_start=row['Start Date']
        end_date=row['End Date']
        while(days_30>=0):
            
            ## Deriving the new end date
            if days_30>1:
                new_end=new_start+ timedelta(days=29)  
            ## Placing the actual end date as the derived end date in the last iteration
            elif days_30==1:
                new_end=end_date
            else:
                new_end=end_date

            ## Appending the transformed records into the dataframe
            if(days_30!=0):
                df_new=df_new.append({'Order ID':row['Order ID'],'Start Date':row['Start Date'],'End Date':row['End Date'],'Difference':row['Difference'],'Split Start Date':new_start,'Split End Date':new_end},ignore_index=True)
            
            ## Updatig the loop values
            if((days_30>0) and (days_30<1)):
                days_decimal=days_30_b-days_changed
                days_changed=days_changed+days_decimal
                new_start=new_end
                days_30=days_30-days_decimal
            else:
                days_changed=days_changed+1
                days_30=days_30-1
                new_start=new_end+ timedelta(days=1)
                
    ## Identifying the records which has difference less than 30
    if(list(data_date.loc[index:index,'Difference'])[0]<30):
        #print(df_new.append({'Order ID':row['Order ID'],'Start Date':row['Start Date'],'End Date':row['End Date'],'Difference':row['Difference'],'Split Start Date':row['Split Start Date'],'Split End Date':row['Split End Date']},ignore_index=True))
        df_new=df_new.append({'Order ID':row['Order ID'],'Start Date':row['Start Date'],'End Date':row['End Date'],'Difference':row['Difference'],'Split Start Date':row['Split Start Date'],'Split End Date':row['Split End Date']},ignore_index=True)

In [71]:
df_new

,Order ID,Start Date,End Date,Split Start Date,Split End Date,Difference
0,SL158,2015-09-08,2015-09-09,2015-09-08,2015-09-09,1.0
1,SL159,2015-09-08,2015-09-09,2015-09-08,2015-09-09,1.0
2,SL160,2015-09-08,2015-09-09,2015-09-08,2015-09-09,1.0
3,SL162,2015-09-10,2015-09-11,2015-09-10,2015-09-11,1.0
4,SL164,2015-09-11,2015-12-10,2015-09-11,2015-10-10,90.0
5,SL164,2015-09-11,2015-12-10,2015-10-11,2015-11-09,90.0
6,SL164,2015-09-11,2015-12-10,2015-11-10,2015-12-10,90.0
7,SL165,2015-09-11,2015-09-12,2015-09-11,2015-09-12,1.0
8,SL168,2015-09-12,2015-12-11,2015-09-12,2015-10-11,90.0
9,SL168,2015-09-12,2015-12-11,2015-10-12,2015-11-10,90.0
10,SL168,2015-09-12,2015-12-11,2015-11-11,2015-12-11,90.0
11,SL169,2015-09-12,2015-09-13,2015-09-12,2015-09-13,1.0
12,SL170,2015-09-12,2015-09-13,2015-09-12,2015-09-13,1.0
13,SL171,2015-09-12,2015-09-13,2015-09-12,2015-09-13,1.0
14,SL172,2015-09-12,2015-09-13,2015-09-12,2015-09-13,1.0
15,SL176,2015-09-13,2015-09-14,2015-09-13,2015-09-14,1.0
16,SL177,2015-09-13,2015-09-14,2015-09-13,2015-09-14,1.0
17,SL178,2015-09-13,2015-09-15,2015-09-13,2015-09-15,2.0
18,SL179,2015-09-13,2015-09-14,2015-09-13,2015-09-14,1.0
19,SL180,2015-09-13,2015-09-14,2015-09-13,2015-09-14,1.0
20,SL183,2015-09-14,2015-09-15,2015-09-14,2015-09-15,1.0
21,SL184,2015-09-14,2015-09-15,2015-09-14,2015-09-15,1.0
22,SL190,2015-09-15,2015-12-14,2015-09-15,2015-10-14,90.0
23,SL190,2015-09-15,2015-12-14,2015-10-15,2015-11-13,90.0
24,SL190,2015-09-15,2015-12-14,2015-11-14,2015-12-14,90.0
25,SL191,2015-09-15,2015-09-16,2015-09-15,2015-09-16,1.0
26,SL192,2015-09-15,2015-09-16,2015-09-15,2015-09-16,1.0
27,SL193,2015-09-15,2015-09-16,2015-09-15,2015-09-16,1.0
28,SL195,2015-09-16,2015-12-15,2015-09-16,2015-10-15,90.0
29,SL195,2015-09-16,2015-12-15,2015-10-16,2015-11-14,90.0
30,SL195,2015-09-16,2015-12-15,2015-11-15,2015-12-15,90.0
31,SL196,2015-09-16,2015-09-17,2015-09-16,2015-09-17,1.0
32,SL199,2015-09-17,2015-12-16,2015-09-17,2015-10-16,90.0
33,SL199,2015-09-17,2015-12-16,2015-10-17,2015-11-15,90.0
34,SL199,2015-09-17,2015-12-16,2015-11-16,2015-12-16,90.0
35,SL200,2015-09-17,2015-09-18,2015-09-17,2015-09-18,1.0
36,SL201,2015-09-17,2015-09-18,2015-09-17,2015-09-18,1.0
37,SL207,2015-09-18,2015-12-17,2015-09-18,2015-10-17,90.0
38,SL207,2015-09-18,2015-12-17,2015-10-18,2015-11-16,90.0
39,SL207,2015-09-18,2015-12-17,2015-11-17,2015-12-17,90.0
40,SL208,2015-09-18,2015-09-19,2015-09-18,2015-09-19,1.0
41,SL209,2015-09-18,2015-09-20,2015-09-18,2015-09-20,2.0
42,SL218,2015-09-20,2015-09-21,2015-09-20,2015-09-21,1.0
43,SL219,2015-09-20,2015-09-21,2015-09-20,2015-09-21,1.0
44,SL223,2015-09-21,2015-09-23,2015-09-21,2015-09-23,2.0
45,SL224,2015-09-21,2015-09-22,2015-09-21,2015-09-22,1.0
46,SL226,2015-09-22,2015-09-23,2015-09-22,2015-09-23,1.0
47,SL227,2015-09-22,2015-09-23,2015-09-22,2015-09-23,1.0
48,SL229,2015-09-23,2015-12-22,2015-09-23,2015-10-22,90.0
49,SL229,2015-09-23,2015-12-22,2015-10-23,2015-11-21,90.0
50,SL229,2015-09-23,2015-12-22,2015-11-22,2015-12-22,90.0
51,SL232,2015-09-24,2015-12-23,2015-09-24,2015-10-23,90.0
52,SL232,2015-09-24,2015-12-23,2015-10-24,2015-11-22,90.0
53,SL232,2015-09-24,2015-12-23,2015-11-23,2015-12-23,90.0
54,SL233,2015-09-24,2015-12-23,2015-09-24,2015-10-23,90.0
55,SL233,2015-09-24,2015-12-23,2015-10-24,2015-11-22,90.0
56,SL233,2015-09-24,2015-12-23,2015-11-23,2015-12-23,90.0
57,SL234,2015-09-24,2015-09-25,2015-09-24,2015-09-25,1.0
58,SL235,2015-09-24,2015-09-25,2015-09-24,2015-09-25,1.0
59,SL239,2015-09-25,2015-12-24,2015-09-25,2015-10-24,90.0
60,SL239,2015-09-25,2015-12-24,2015-10-25,2015-11-23,90.0
61,SL239,2015-09-25,2015-12-24,2015-11-24,2015-12-24,90.0
62,SL240,2015-09-25,2015-12-24,2015-09-25,2015-10-24,90.0
63,SL240,2015-09-25,2015-12-24,2015-10-25,2015-11-23,90.0
64,SL240,2015-09-25,2015-12-24,2015-11-24,2015-12-24,90.0
65,SL241,2015-09-25,2015-11-24,2015-09-25,2015-10-24,60.0
66,SL241,2015-09-25,2015-11-24,2015-10-25,2015-11-24,60.0
67,SL242,2015-09-25,2015-09-26,2015-09-25,2015-09-26,1.0
68,SL243,2015-09-25,2015-09-26,2015-09-25,2015-09-26,1.0
69,SL251,2015-09-27,2015-12-26,2015-09-27,2015-10-26,90.0
70,SL251,2015-09-27,2015-12-26,2015-10-27,2015-11-25,90.0
71,SL251,2015-09-27,2015-12-26,2015-11-26,2015-12-26,90.0
72,SL252,2015-09-27,2015-12-26,2015-09-27,2015-10-26,90.0
73,SL252,2015-09-27,2015-12-26,2015-10-27,2015-11-25,90.0
74,SL252,2015-09-27,2015-12-26,2015-11-26,2015-12-26,90.0
75,SL257,2015-09-28,2015-12-27,2015-09-28,2015-10-27,90.0
76,SL257,2015-09-28,2015-12-27,2015-10-28,2015-11-26,90.0
77,SL257,2015-09-28,2015-12-27,2015-11-27,2015-12-27,90.0
78,SL258,2015-09-28,2015-11-27,2015-09-28,2015-10-27,60.0
79,SL258,2015-09-28,2015-11-27,2015-10-28,2015-11-27,60.0
80,SL260,2015-09-29,2015-12-28,2015-09-29,2015-10-28,90.0
81,SL260,2015-09-29,2015-12-28,2015-10-29,2015-11-27,90.0
82,SL260,2015-09-29,2015-12-28,2015-11-28,2015-12-28,90.0
83,SL262,2015-09-29,2015-09-30,2015-09-29,2015-09-30,1.0
84,SL266,2015-09-30,2015-10-02,2015-09-30,2015-10-02,2.0
85,SL267,2015-09-30,2015-10-01,2015-09-30,2015-10-01,1.0
86,SL268,2015-09-30,2015-10-01,2015-09-30,2015-10-01,1.0
87,SL269,2015-09-30,2015-10-02,2015-09-30,2015-10-02,2.0
88,SL277,2015-10-01,2015-12-30,2015-10-01,2015-10-30,90.0
89,SL277,2015-10-01,2015-12-30,2015-10-31,2015-11-29,90.0
90,SL277,2015-10-01,2015-12-30,2015-11-30,2015-12-30,90.0
91,SL278,2015-10-01,2015-12-30,2015-10-01,2015-10-30,90.0
92,SL278,2015-10-01,2015-12-30,2015-10-31,2015-11-29,90.0
93,SL278,2015-10-01,2015-12-30,2015-11-30,2015-12-30,90.0
94,SL279,2015-10-01,2015-12-30,2015-10-01,2015-10-30,90.0
95,SL279,2015-10-01,2015-12-30,2015-10-31,2015-11-29,90.0
96,SL279,2015-10-01,2015-12-30,2015-11-30,2015-12-30,90.0
97,SL281,2015-10-01,2015-10-03,2015-10-01,2015-10-03,2.0
98,SL287,2015-10-02,2015-12-31,2015-10-02,2015-10-31,90.0
99,SL287,2015-10-02,2015-12-31,2015-11-01,2015-11-30,90.0
100,SL287,2015-10-02,2015-12-31,2015-12-01,2015-12-31,90.0
101,SL288,2015-10-02,2015-12-31,2015-10-02,2015-10-31,90.0
102,SL288,2015-10-02,2015-12-31,2015-11-01,2015-11-30,90.0
103,SL288,2015-10-02,2015-12-31,2015-12-01,2015-12-31,90.0
104,SL289,2015-10-02,2015-10-03,2015-10-02,2015-10-03,1.0
105,SL300,2015-10-03,2016-01-01,2015-10-03,2015-11-01,90.0
106,SL300,2015-10-03,2016-01-01,2015-11-02,2015-12-01,90.0
107,SL300,2015-10-03,2016-01-01,2015-12-02,2016-01-01,90.0
108,SL301,2015-10-03,2016-01-01,2015-10-03,2015-11-01,90.0
109,SL301,2015-10-03,2016-01-01,2015-11-02,2015-12-01,90.0
110,SL301,2015-10-03,2016-01-01,2015-12-02,2016-01-01,90.0
111,SL303,2015-10-03,2015-10-04,2015-10-03,2015-10-04,1.0
112,SL304,2015-10-03,2015-10-04,2015-10-03,2015-10-04,1.0
113,SL305,2015-10-03,2015-10-04,2015-10-03,2015-10-04,1.0
114,SL315,2015-10-05,2016-01-03,2015-10-05,2015-11-03,90.0
115,SL315,2015-10-05,2016-01-03,2015-11-04,2015-12-03,90.0
116,SL315,2015-10-05,2016-01-03,2015-12-04,2016-01-03,90.0
117,SL316,2015-10-05,2015-10-06,2015-10-05,2015-10-06,1.0
118,SL323,2015-10-06,2015-10-07,2015-10-06,2015-10-07,1.0
119,SL328,2015-10-07,2016-01-05,2015-10-07,2015-11-05,90.0
120,SL328,2015-10-07,2016-01-05,2015-11-06,2015-12-05,90.0
121,SL328,2015-10-07,2016-01-05,2015-12-06,2016-01-05,90.0
122,SL334,2015-10-08,2015-10-09,2015-10-08,2015-10-09,1.0
123,SL335,2015-10-08,2015-10-09,2015-10-08,2015-10-09,1.0
124,SL336,2015-10-08,2015-10-09,2015-10-08,2015-10-09,1.0
125,SL337,2015-10-08,2015-10-09,2015-10-08,2015-10-09,1.0
126,SL340,2015-10-09,2016-01-07,2015-10-09,2015-11-07,90.0
127,SL340,2015-10-09,2016-01-07,2015-11-08,2015-12-07,90.0
128,SL340,2015-10-09,2016-01-07,2015-12-08,2016-01-07,90.0
129,SL341,2015-10-09,2016-01-07,2015-10-09,2015-11-07,90.0
130,SL341,2015-10-09,2016-01-07,2015-11-08,2015-12-07,90.0
131,SL341,2015-10-09,2016-01-07,2015-12-08,2016-01-07,90.0
132,SL342,2015-10-09,2016-01-07,2015-10-09,2015-11-07,90.0
133,SL342,2015-10-09,2016-01-07,2015-11-08,2015-12-07,90.0
134,SL342,2015-10-09,2016-01-07,2015-12-08,2016-01-07,90.0
135,SL343,2015-10-09,2015-10-10,2015-10-09,2015-10-10,1.0
136,SL344,2015-10-09,2015-10-10,2015-10-09,2015-10-10,1.0
137,SL345,2015-10-09,2015-10-10,2015-10-09,2015-10-10,1.0
138,SL350,2015-10-10,2016-01-08,2015-10-10,2015-11-08,90.0
139,SL350,2015-10-10,2016-01-08,2015-11-09,2015-12-08,90.0
140,SL350,2015-10-10,2016-01-08,2015-12-09,2016-01-08,90.0
141,SL351,2015-10-10,2016-01-08,2015-10-10,2015-11-08,90.0
142,SL351,2015-10-10,2016-01-08,2015-11-09,2015-12-08,90.0
143,SL351,2015-10-10,2016-01-08,2015-12-09,2016-01-08,90.0
144,SL352,2015-10-10,2015-10-11,2015-10-10,2015-10-11,1.0
145,SL353,2015-10-10,2015-10-11,2015-10-10,2015-10-11,1.0
146,SL354,2015-10-10,2015-10-11,2015-10-10,2015-10-11,1.0
147,SL355,2015-10-10,2015-10-11,2015-10-10,2015-10-11,1.0
148,SL363,2015-10-11,2016-01-09,2015-10-11,2015-11-09,90.0
149,SL363,2015-10-11,2016-01-09,2015-11-10,2015-12-09,90.0
150,SL363,2015-10-11,2016-01-09,2015-12-10,2016-01-09,90.0
151,SL364,2015-10-11,2016-01-09,2015-10-11,2015-11-09,90.0
152,SL364,2015-10-11,2016-01-09,2015-11-10,2015-12-09,90.0
153,SL364,2015-10-11,2016-01-09,2015-12-10,2016-01-09,90.0
154,SL365,2015-10-11,2016-01-09,2015-10-11,2015-11-09,90.0
155,SL365,2015-10-11,2016-01-09,2015-11-10,2015-12-09,90.0
156,SL365,2015-10-11,2016-01-09,2015-12-10,2016-01-09,90.0
157,SL366,2015-10-11,2015-10-13,2015-10-11,2015-10-13,2.0
158,SL367,2015-10-11,2015-10-18,2015-10-11,2015-10-18,7.0
159,SL368,2015-10-11,2015-10-12,2015-10-11,2015-10-12,1.0
160,SL369,2015-10-11,2015-10-18,2015-10-11,2015-10-18,7.0
161,SL370,2015-10-11,2015-10-12,2015-10-11,2015-10-12,1.0
162,SL376,2015-10-12,2016-01-10,2015-10-12,2015-11-10,90.0
163,SL376,2015-10-12,2016-01-10,2015-11-11,2015-12-10,90.0
164,SL376,2015-10-12,2016-01-10,2015-12-11,2016-01-10,90.0
165,SL377,2015-10-12,2016-01-10,2015-10-12,2015-11-10,90.0
166,SL377,2015-10-12,2016-01-10,2015-11-11,2015-12-10,90.0
167,SL377,2015-10-12,2016-01-10,2015-12-11,2016-01-10,90.0
168,SL378,2015-10-12,2016-01-10,2015-10-12,2015-11-10,90.0
169,SL378,2015-10-12,2016-01-10,2015-11-11,2015-12-10,90.0
170,SL378,2015-10-12,2016-01-10,2015-12-11,2016-01-10,90.0
171,SL379,2015-10-12,2015-10-13,2015-10-12,2015-10-13,1.0
172,SL380,2015-10-12,2015-10-13,2015-10-12,2015-10-13,1.0
173,SL381,2015-10-12,2015-10-13,2015-10-12,2015-10-13,1.0
174,SL382,2015-10-12,2015-10-13,2015-10-12,2015-10-13,1.0
175,SL384,2015-10-12,2015-10-13,2015-10-12,2015-10-13,1.0
176,SL385,2015-10-12,2015-10-13,2015-10-12,2015-10-13,1.0
177,SL1217,2015-11-03,2016-03-02,2015-11-03,2015-12-02,120.0
178,SL1217,2015-11-03,2016-03-02,2015-12-03,2016-01-01,120.0
179,SL1217,2015-11-03,2016-03-02,2016-01-02,2016-01-31,120.0
180,SL1217,2015-11-03,2016-03-02,2016-02-01,2016-03-02,120.0
181,SL1452,2015-12-21,2016-07-16,2015-12-21,2016-01-19,208.0
182,SL1452,2015-12-21,2016-07-16,2016-01-20,2016-02-18,208.0
183,SL1452,2015-12-21,2016-07-16,2016-02-19,2016-03-19,208.0
184,SL1452,2015-12-21,2016-07-16,2016-03-20,2016-04-18,208.0
185,SL1452,2015-12-21,2016-07-16,2016-04-19,2016-05-18,208.0
186,SL1452,2015-12-21,2016-07-16,2016-05-19,2016-06-17,208.0
187,SL1452,2015-12-21,2016-07-16,2016-06-18,2016-07-16,208.0
188,SL4348,2016-09-22,2016-10-04,2016-09-22,2016-10-04,12.0
189,SL4738,2016-09-15,2016-11-14,2016-09-15,2016-10-14,60.0
190,SL4738,2016-09-15,2016-11-14,2016-10-15,2016-11-14,60.0
191,SL5319,2016-09-22,2016-11-07,2016-09-22,2016-10-21,46.0
192,SL5319,2016-09-22,2016-11-07,2016-10-22,2016-11-07,46.0
193,SL6244,2016-11-23,2017-01-22,2016-11-23,2016-12-22,60.0
194,SL6244,2016-11-23,2017-01-22,2016-12-23,2017-01-22,60.0
195,SL6855,2016-12-21,2017-02-21,2016-12-21,2017-01-19,62.0
196,SL6855,2016-12-21,2017-02-21,2017-01-20,2017-02-18,62.0
197,SL6855,2016-12-21,2017-02-21,2017-02-19,2017-02-21,62.0
198,SL6997,2016-12-30,2017-06-30,2016-12-30,2017-01-28,182.0
199,SL6997,2016-12-30,2017-06-30,2017-01-29,2017-02-27,182.0
200,SL6997,2016-12-30,2017-06-30,2017-02-28,2017-03-29,182.0
201,SL6997,2016-12-30,2017-06-30,2017-03-30,2017-04-28,182.0
202,SL6997,2016-12-30,2017-06-30,2017-04-29,2017-05-28,182.0
203,SL6997,2016-12-30,2017-06-30,2017-05-29,2017-06-27,182.0
204,SL6997,2016-12-30,2017-06-30,2017-06-28,2017-06-30,182.0
205,SLB1253161,2017-07-15,2017-08-13,2017-07-15,2017-08-13,29.0
206,SLB2970530,2017-10-14,2017-04-11,2017-10-14,2017-04-11,-186.0
207,SLB27287329,2017-05-13,2017-07-12,2017-05-13,2017-06-11,60.0
208,SLB27287329,2017-05-13,2017-07-12,2017-06-12,2017-07-12,60.0
209,SLB36502009,2017-04-01,2017-09-27,2017-04-01,2017-04-30,179.0
210,SLB36502009,2017-04-01,2017-09-27,2017-05-01,2017-05-30,179.0
211,SLB36502009,2017-04-01,2017-09-27,2017-05-31,2017-06-29,179.0
212,SLB36502009,2017-04-01,2017-09-27,2017-06-30,2017-07-29,179.0
213,SLB36502009,2017-04-01,2017-09-27,2017-07-30,2017-08-28,179.0
214,SLB36502009,2017-04-01,2017-09-27,2017-08-29,2017-09-27,179.0
215,SLB82838226,2017-05-06,2017-06-04,2017-05-06,2017-06-04,29.0
216,SLB90244936,2017-09-30,2017-12-29,2017-09-30,2017-10-29,90.0
217,SLB90244936,2017-09-30,2017-12-29,2017-10-30,2017-11-28,90.0
218,SLB90244936,2017-09-30,2017-12-29,2017-11-29,2017-12-29,90.0
219,SLB99701642,2017-05-05,2017-06-03,2017-05-05,2017-06-03,29.0
220,SLH5317239,2017-07-03,2017-11-30,2017-07-03,2017-08-01,150.0
221,SLH5317239,2017-07-03,2017-11-30,2017-08-02,2017-08-31,150.0
222,SLH5317239,2017-07-03,2017-11-30,2017-09-01,2017-09-30,150.0
223,SLH5317239,2017-07-03,2017-11-30,2017-10-01,2017-10-30,150.0
224,SLH5317239,2017-07-03,2017-11-30,2017-10-31,2017-11-30,150.0
225,SLH44727392,2017-05-15,2017-07-13,2017-05-15,2017-06-13,59.0
226,SLH44727392,2017-05-15,2017-07-13,2017-06-14,2017-07-13,59.0
227,SLH45803004,2017-04-19,2017-05-18,2017-04-19,2017-05-18,29.0
228,SLH57801072,2017-07-03,2017-10-01,2017-07-03,2017-08-01,90.0
229,SLH57801072,2017-07-03,2017-10-01,2017-08-02,2017-08-31,90.0
230,SLH57801072,2017-07-03,2017-10-01,2017-09-01,2017-10-01,90.0
231,SL1134,2015-12-21,2015-12-22,2015-12-21,2015-12-22,1.0
232,SL1011,2015-09-07,2015-12-07,2015-09-07,2015-10-06,91.0
233,SL1011,2015-09-07,2015-12-07,2015-10-07,2015-11-05,91.0
234,SL1011,2015-09-07,2015-12-07,2015-11-06,2015-12-05,91.0
235,SL1011,2015-09-07,2015-12-07,2015-12-06,2015-12-07,91.0
236,SL1134,2015-10-14,2016-01-14,2015-10-14,2015-11-12,92.0
237,SL1134,2015-10-14,2016-01-14,2015-11-13,2015-12-12,92.0
238,SL1134,2015-10-14,2016-01-14,2015-12-13,2016-01-11,92.0
239,SL1134,2015-10-14,2016-01-14,2016-01-12,2016-01-14,92.0
240,SL3686,2016-08-21,2016-12-30,2016-08-21,2016-09-19,131.0
241,SL3686,2016-08-21,2016-12-30,2016-09-20,2016-10-19,131.0
242,SL3686,2016-08-21,2016-12-30,2016-10-20,2016-11-18,131.0
243,SL3686,2016-08-21,2016-12-30,2016-11-19,2016-12-18,131.0
244,SL3686,2016-08-21,2016-12-30,2016-12-19,2016-12-30,131.0
245,SL3691,2016-08-21,2016-09-21,2016-08-21,2016-09-19,31.0
246,SL3691,2016-08-21,2016-09-21,2016-09-20,2016-09-21,31.0
247,SL3695,2016-08-23,2016-09-23,2016-08-23,2016-09-21,31.0
248,SL3695,2016-08-23,2016-09-23,2016-09-22,2016-09-23,31.0
249,SL3721,2016-08-22,2016-09-22,2016-08-22,2016-09-20,31.0
250,SL3721,2016-08-22,2016-09-22,2016-09-21,2016-09-22,31.0
251,SL5245,2016-10-09,2016-11-19,2016-10-09,2016-11-07,41.0
252,SL5245,2016-10-09,2016-11-19,2016-11-08,2016-11-19,41.0
253,SL5255,2016-10-22,2016-12-21,2016-10-22,2016-11-20,60.0
254,SL5255,2016-10-22,2016-12-21,2016-11-21,2016-12-21,60.0
255,SL11333,2017-04-17,2017-10-14,2017-04-17,2017-05-16,180.0
256,SL11333,2017-04-17,2017-10-14,2017-05-17,2017-06-15,180.0
257,SL11333,2017-04-17,2017-10-14,2017-06-16,2017-07-15,180.0
258,SL11333,2017-04-17,2017-10-14,2017-07-16,2017-08-14,180.0
259,SL11333,2017-04-17,2017-10-14,2017-08-15,2017-09-13,180.0
260,SL11333,2017-04-17,2017-10-14,2017-09-14,2017-10-14,180.0
261,SL11338,2017-04-17,2017-09-30,2017-04-17,2017-05-16,166.0
262,SL11338,2017-04-17,2017-09-30,2017-05-17,2017-06-15,166.0
263,SL11338,2017-04-17,2017-09-30,2017-06-16,2017-07-15,166.0
264,SL11338,2017-04-17,2017-09-30,2017-07-16,2017-08-14,166.0
265,SL11338,2017-04-17,2017-09-30,2017-08-15,2017-09-13,166.0
266,SL11338,2017-04-17,2017-09-30,2017-09-14,2017-09-30,166.0
267,SL11365,2017-04-16,2017-07-15,2017-04-16,2017-05-15,90.0
268,SL11365,2017-04-16,2017-07-15,2017-05-16,2017-06-14,90.0
269,SL11365,2017-04-16,2017-07-15,2017-06-15,2017-07-15,90.0
270,SL11377,2017-04-14,2017-05-13,2017-04-14,2017-05-13,29.0
271,SL11384,2017-04-17,2017-10-14,2017-04-17,2017-05-16,180.0
272,SL11384,2017-04-17,2017-10-14,2017-05-17,2017-06-15,180.0
273,SL11384,2017-04-17,2017-10-14,2017-06-16,2017-07-15,180.0
274,SL11384,2017-04-17,2017-10-14,2017-07-16,2017-08-14,180.0
275,SL11384,2017-04-17,2017-10-14,2017-08-15,2017-09-13,180.0
276,SL11384,2017-04-17,2017-10-14,2017-09-14,2017-10-14,180.0
277,SL10058,2017-04-04,2017-07-03,2017-04-04,2017-05-03,90.0
278,SL10058,2017-04-04,2017-07-03,2017-05-04,2017-06-02,90.0
279,SL10058,2017-04-04,2017-07-03,2017-06-03,2017-07-03,90.0
280,SL10070,2017-04-04,2017-07-03,2017-04-04,2017-05-03,90.0
281,SL10070,2017-04-04,2017-07-03,2017-05-04,2017-06-02,90.0
282,SL10070,2017-04-04,2017-07-03,2017-06-03,2017-07-03,90.0
283,SL10092,2017-04-03,2017-07-02,2017-04-03,2017-05-02,90.0
284,SL10092,2017-04-03,2017-07-02,2017-05-03,2017-06-01,90.0
285,SL10092,2017-04-03,2017-07-02,2017-06-02,2017-07-02,90.0
286,SL11366,2017-04-18,2017-07-17,2017-04-18,2017-05-17,90.0
287,SL11366,2017-04-18,2017-07-17,2017-05-18,2017-06-16,90.0
288,SL11366,2017-04-18,2017-07-17,2017-06-17,2017-07-17,90.0
289,SL99765989,2017-04-26,2017-10-23,2017-04-26,2017-05-25,180.0
290,SL99765989,2017-04-26,2017-10-23,2017-05-26,2017-06-24,180.0
291,SL99765989,2017-04-26,2017-10-23,2017-06-25,2017-07-24,180.0
292,SL99765989,2017-04-26,2017-10-23,2017-07-25,2017-08-23,180.0
293,SL99765989,2017-04-26,2017-10-23,2017-08-24,2017-09-22,180.0
294,SL99765989,2017-04-26,2017-10-23,2017-09-23,2017-10-23,180.0
295,SL99854931,2017-04-19,2017-08-17,2017-04-19,2017-05-18,120.0
296,SL99854931,2017-04-19,2017-08-17,2017-05-19,2017-06-17,120.0
297,SL99854931,2017-04-19,2017-08-17,2017-06-18,2017-07-17,120.0
298,SL99854931,2017-04-19,2017-08-17,2017-07-18,2017-08-17,120.0
299,SL99878606,2017-03-25,2017-09-21,2017-03-25,2017-04-23,180.0
300,SL99878606,2017-03-25,2017-09-21,2017-04-24,2017-05-23,180.0
301,SL99878606,2017-03-25,2017-09-21,2017-05-24,2017-06-22,180.0
302,SL99878606,2017-03-25,2017-09-21,2017-06-23,2017-07-22,180.0
303,SL99878606,2017-03-25,2017-09-21,2017-07-23,2017-08-21,180.0
304,SL99878606,2017-03-25,2017-09-21,2017-08-22,2017-09-21,180.0
305,SL99915921,2017-04-25,2020-04-14,2017-04-25,2017-05-24,1085.0
306,SL99915921,2017-04-25,2020-04-14,2017-05-25,2017-06-23,1085.0
307,SL99915921,2017-04-25,2020-04-14,2017-06-24,2017-07-23,1085.0
308,SL99915921,2017-04-25,2020-04-14,2017-07-24,2017-08-22,1085.0
309,SL99915921,2017-04-25,2020-04-14,2017-08-23,2017-09-21,1085.0
310,SL99915921,2017-04-25,2020-04-14,2017-09-22,2017-10-21,1085.0
311,SL99915921,2017-04-25,2020-04-14,2017-10-22,2017-11-20,1085.0
312,SL99915921,2017-04-25,2020-04-14,2017-11-21,2017-12-20,1085.0
313,SL99915921,2017-04-25,2020-04-14,2017-12-21,2018-01-19,1085.0
314,SL99915921,2017-04-25,2020-04-14,2018-01-20,2018-02-18,1085.0
315,SL99915921,2017-04-25,2020-04-14,2018-02-19,2018-03-20,1085.0
316,SL99915921,2017-04-25,2020-04-14,2018-03-21,2018-04-19,1085.0
317,SL99915921,2017-04-25,2020-04-14,2018-04-20,2018-05-19,1085.0
318,SL99915921,2017-04-25,2020-04-14,2018-05-20,2018-06-18,1085.0
319,SL99915921,2017-04-25,2020-04-14,2018-06-19,2018-07-18,1085.0
320,SL99915921,2017-04-25,2020-04-14,2018-07-19,2018-08-17,1085.0
321,SL99915921,2017-04-25,2020-04-14,2018-08-18,2018-09-16,1085.0
322,SL99915921,2017-04-25,2020-04-14,2018-09-17,2018-10-16,1085.0
323,SL99915921,2017-04-25,2020-04-14,2018-10-17,2018-11-15,1085.0
324,SL99915921,2017-04-25,2020-04-14,2018-11-16,2018-12-15,1085.0
325,SL99915921,2017-04-25,2020-04-14,2018-12-16,2019-01-14,1085.0
326,SL99915921,2017-04-25,2020-04-14,2019-01-15,2019-02-13,1085.0
327,SL99915921,2017-04-25,2020-04-14,2019-02-14,2019-03-15,1085.0
328,SL99915921,2017-04-25,2020-04-14,2019-03-16,2019-04-14,1085.0
329,SL99915921,2017-04-25,2020-04-14,2019-04-15,2019-05-14,1085.0